apiVersion: v1
kind: Pod
metadata:
  labels:
    some-label: jenkins-pipeline
spec:
  serviceAccountName: default # Enter the service account name being used
  securityContext:
    runAsUser: 0
    fsGroup: 0
    runAsNonRoot: false
  containers:
  - name: jenkins-docker-agent
    image: amazon/aws-cli #docker:latest Enter the jenkins inbound agent image.
    command:
    - cat
    tty: true
    volumeMounts:
    - mountPath: /var/run/docker.sock
      name: docker-sock
  volumes:
  - name: docker-sock
    hostPath:
      path: /var/run/docker.sock
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: "1"
        memory: 1024Mi
